// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab
{

    // AnnouncementAttach
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class AnnouncementAttach
    {

        ///<summary>
        /// 公告附件流水識別碼
        ///</summary>
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 公告流水識別碼
        ///</summary>
        public int AnnouncementId { get; set; } // AnnouncementId

        ///<summary>
        /// 檔案顯示名稱
        ///</summary>
        public string DispalyFileName { get; set; } // DispalyFileName (length: 200)

        ///<summary>
        /// 附加檔案儲存路徑
        ///</summary>
        public string AttachFilePath { get; set; } // AttachFilePath (length: 200)

        ///<summary>
        /// 附件類型(一般附件:1 影片：2)
        ///</summary>
        public byte AttachType { get; set; } // AttachType

        ///<summary>
        /// 是否有效
        ///</summary>
        public bool Valid { get; set; } // Valid

        ///<summary>
        /// 建立人員
        ///</summary>
        public string CreatorId { get; set; } // CreatorId (length: 50)

        ///<summary>
        /// 建檔時間
        ///</summary>
        public System.DateTime CreatedAt { get; set; } // CreatedAt

        ///<summary>
        /// 維護人員
        ///</summary>
        public string ModifierId { get; set; } // ModifierId (length: 50)

        ///<summary>
        /// 維護時間
        ///</summary>
        public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

        ///<summary>
        /// 建立人
        ///</summary>
        public string CreateBy { get; set; } // CreateBy (length: 50)

        ///<summary>
        /// 建立時間
        ///</summary>
        public System.DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 更新人
        ///</summary>
        public string UpdateBy { get; set; } // UpdateBy (length: 50)

        ///<summary>
        /// 更新時間
        ///</summary>
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        public AnnouncementAttach()
        {
            AttachType = 0;
            Valid = false;
            CreatedAt = System.DateTime.UtcNow;
            CreateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
