// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab
{

    // Announcement
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class AnnouncementConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Announcement>
    {
        public AnnouncementConfiguration()
            : this("dbo")
        {
        }

        public AnnouncementConfiguration(string schema)
        {
            ToTable("Announcement", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CategoryId).HasColumnName(@"CategoryId").IsRequired().HasColumnType("int");
            Property(x => x.Title).HasColumnName(@"Title").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.ContentSummary).HasColumnName(@"ContentSummary").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.ContentDesc).HasColumnName(@"ContentDesc").IsRequired().HasColumnType("nvarchar(max)");
            Property(x => x.EffectiveStartdate).HasColumnName(@"EffectiveStartdate").IsRequired().HasColumnType("datetime");
            Property(x => x.EffectiveEnddate).HasColumnName(@"EffectiveEnddate").IsRequired().HasColumnType("datetime");
            Property(x => x.BackgroundImagePath).HasColumnName(@"BackgroundImagePath").IsOptional().HasColumnType("nvarchar").HasMaxLength(100);
            Property(x => x.Valid).HasColumnName(@"Valid").IsRequired().HasColumnType("bit");
            Property(x => x.CreatorName).HasColumnName(@"CreatorName").IsRequired().HasColumnType("nvarchar").HasMaxLength(20);
            Property(x => x.CreatorDept).HasColumnName(@"CreatorDept").IsRequired().HasColumnType("int");
            Property(x => x.CreatorId).HasColumnName(@"CreatorId").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").IsRequired().HasColumnType("datetime");
            Property(x => x.ModifierId).HasColumnName(@"ModifierId").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").IsOptional().HasColumnType("datetime");
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").IsOptional().HasColumnType("datetime");
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").IsOptional().HasColumnType("datetime");
        }
    }

}
// </auto-generated>
