// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab
{

    // ApplicationErrorLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class ApplicationErrorLogConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ApplicationErrorLog>
    {
        public ApplicationErrorLogConfiguration()
            : this("dbo")
        {
        }

        public ApplicationErrorLogConfiguration(string schema)
        {
            ToTable("ApplicationErrorLog", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ApplicationName).HasColumnName(@"ApplicationName").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.RequestUrl).HasColumnName(@"RequestUrl").IsOptional().HasColumnType("nvarchar").HasMaxLength(20);
            Property(x => x.RequestPath).HasColumnName(@"RequestPath").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.Message).HasColumnName(@"Message").IsRequired().HasColumnType("nvarchar").HasMaxLength(500);
            Property(x => x.StachMessage).HasColumnName(@"StachMessage").IsRequired().HasColumnType("ntext").IsMaxLength();
            Property(x => x.LogAt).HasColumnName(@"LogAt").IsRequired().HasColumnType("datetime");
        }
    }

}
// </auto-generated>
