// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab
{

    // Brand
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class BrandConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Brand>
    {
        public BrandConfiguration()
            : this("dbo")
        {
        }

        public BrandConfiguration(string schema)
        {
            ToTable("Brand", schema);
            HasKey(x => x.BrandId);

            Property(x => x.BrandId).HasColumnName(@"BrandId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BrandName).HasColumnName(@"BrandName").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Valid).HasColumnName(@"Valid").IsRequired().HasColumnType("bit");
            Property(x => x.CreatorId).HasColumnName(@"CreatorId").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").IsRequired().HasColumnType("datetime");
            Property(x => x.ModifierId).HasColumnName(@"ModifierId").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.ModifiedAt).HasColumnName(@"ModifiedAt").IsOptional().HasColumnType("datetime");
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").IsOptional().HasColumnType("datetime");
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").IsOptional().HasColumnType("datetime");
        }
    }

}
// </auto-generated>
