// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab
{

    // Language
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class LanguageConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Language>
    {
        public LanguageConfiguration()
            : this("dbo")
        {
        }

        public LanguageConfiguration(string schema)
        {
            ToTable("Language", schema);
            HasKey(x => x.PkLanguage);

            Property(x => x.PkLanguage).HasColumnName(@"PK_Language").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.LanguageKey).HasColumnName(@"LanguageKey").IsRequired().HasColumnType("nvarchar").HasMaxLength(10);
            Property(x => x.LanguageName).HasColumnName(@"LanguageName").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.IsNeedUpdate).HasColumnName(@"IsNeedUpdate").IsRequired().HasColumnType("bit");
        }
    }

}
// </auto-generated>
