// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab
{

    // RaiseErrorMessage
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class RaiseErrorMessageConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RaiseErrorMessage>
    {
        public RaiseErrorMessageConfiguration()
            : this("dbo")
        {
        }

        public RaiseErrorMessageConfiguration(string schema)
        {
            ToTable("RaiseErrorMessage", schema);
            HasKey(x => x.ErrorId);

            Property(x => x.ErrorId).HasColumnName(@"ErrorId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.HostName).HasColumnName(@"HostName").IsOptional().HasColumnType("nvarchar").HasMaxLength(100);
            Property(x => x.ProgramName).HasColumnName(@"ProgramName").IsOptional().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.UserName).HasColumnName(@"UserName").IsOptional().HasColumnType("nvarchar").HasMaxLength(100);
            Property(x => x.ErrorNumber).HasColumnName(@"ErrorNumber").IsOptional().HasColumnType("int");
            Property(x => x.ErrorSeverity).HasColumnName(@"ErrorSeverity").IsOptional().HasColumnType("int");
            Property(x => x.ErrorState).HasColumnName(@"ErrorState").IsOptional().HasColumnType("int");
            Property(x => x.ErrorLine).HasColumnName(@"ErrorLine").IsOptional().HasColumnType("int");
            Property(x => x.ErrorProcedure).HasColumnName(@"ErrorProcedure").IsOptional().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.ErrorMessage).HasColumnName(@"ErrorMessage").IsOptional().HasColumnType("nvarchar").HasMaxLength(4000);
            Property(x => x.OccurTime).HasColumnName(@"OccurTime").IsOptional().HasColumnType("datetime");
        }
    }

}
// </auto-generated>
