// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class UspGetBrandsPagingReturnModel
    {
        public System.Int32? TotalRecords { get; set; }
        public System.Int64? RowNumber { get; set; }
        public System.Int64? RowNumber1 { get; set; }
        public System.Int32 BrandId { get; set; }
        public System.String BrandName { get; set; }
    }

}
// </auto-generated>
