// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab.DB
{

    // Announcement
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Announcement
    {

        ///<summary>
        /// 公告流水識別碼
        ///</summary>
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 公告類別Id
        ///</summary>
        public int CategoryId { get; set; } // CategoryId

        ///<summary>
        /// 標題
        ///</summary>
        public string Title { get; set; } // Title (length: 200)

        ///<summary>
        /// 內容摘要
        ///</summary>
        public string ContentSummary { get; set; } // ContentSummary (length: 200)

        ///<summary>
        /// 內容
        ///</summary>
        public string ContentDesc { get; set; } // ContentDesc

        ///<summary>
        /// 公告起日
        ///</summary>
        public System.DateTime EffectiveStartdate { get; set; } // EffectiveStartdate

        ///<summary>
        /// 公告迄日
        ///</summary>
        public System.DateTime EffectiveEnddate { get; set; } // EffectiveEnddate

        ///<summary>
        /// 背景圖案檔案路徑
        ///</summary>
        public string BackgroundImagePath { get; set; } // BackgroundImagePath (length: 100)

        ///<summary>
        /// 是否有效
        ///</summary>
        public bool Valid { get; set; } // Valid

        ///<summary>
        /// 公告人
        ///</summary>
        public string CreatorName { get; set; } // CreatorName (length: 20)

        ///<summary>
        /// 公告單位
        ///</summary>
        public int CreatorDept { get; set; } // CreatorDept

        ///<summary>
        /// 建立人員
        ///</summary>
        public string CreatorId { get; set; } // CreatorId (length: 50)

        ///<summary>
        /// 建檔時間
        ///</summary>
        public System.DateTime CreatedAt { get; set; } // CreatedAt

        ///<summary>
        /// 維護人員
        ///</summary>
        public string ModifierId { get; set; } // ModifierId (length: 50)

        ///<summary>
        /// 維護時間
        ///</summary>
        public System.DateTime? ModifiedAt { get; set; } // ModifiedAt

        ///<summary>
        /// 建立人
        ///</summary>
        public string CreateBy { get; set; } // CreateBy (length: 50)

        ///<summary>
        /// 建立時間
        ///</summary>
        public System.DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 更新人
        ///</summary>
        public string UpdateBy { get; set; } // UpdateBy (length: 50)

        ///<summary>
        /// 更新時間
        ///</summary>
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        public Announcement()
        {
            ContentSummary = "";
            Valid = false;
            CreatorName = "";
            CreatedAt = System.DateTime.UtcNow;
            CreateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
