// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab.DB
{

    // Language
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Language
    {

        ///<summary>
        /// 流水識別碼
        ///</summary>
        public int PkLanguage { get; set; } // PK_Language (Primary key)

        ///<summary>
        /// 語系代碼
        ///</summary>
        public string LanguageKey { get; set; } // LanguageKey (length: 10)

        ///<summary>
        /// 語系名稱
        ///</summary>
        public string LanguageName { get; set; } // LanguageName (length: 50)

        ///<summary>
        /// 語言包是否更新
        ///</summary>
        public bool IsNeedUpdate { get; set; } // IsNeedUpdate

        public Language()
        {
            IsNeedUpdate = false;
        }
    }

}
// </auto-generated>
