// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab.DB
{

    // LanguageInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class LanguageInfoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LanguageInfo>
    {
        public LanguageInfoConfiguration()
            : this("dbo")
        {
        }

        public LanguageInfoConfiguration(string schema)
        {
            ToTable("LanguageInfo", schema);
            HasKey(x => x.PkLanguageInfo);

            Property(x => x.PkLanguageInfo).HasColumnName(@"PK_LanguageInfo").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FkLanguageInfoLanguageKeyLanguageId).HasColumnName(@"FK_LanguageInfo_LanguageKey_Language_ID").IsRequired().HasColumnType("nvarchar").HasMaxLength(10);
            Property(x => x.MsgKey).HasColumnName(@"MsgKey").IsRequired().HasColumnType("nvarchar").HasMaxLength(500);
            Property(x => x.Msg).HasColumnName(@"Msg").IsRequired().HasColumnType("nvarchar").HasMaxLength(500);
        }
    }

}
// </auto-generated>
