// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab.DB
{

    // LanguageInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class LanguageInfo
    {

        ///<summary>
        /// 流水號
        ///</summary>
        public int PkLanguageInfo { get; set; } // PK_LanguageInfo (Primary key)

        ///<summary>
        /// 語系代碼
        ///</summary>
        public string FkLanguageInfoLanguageKeyLanguageId { get; set; } // FK_LanguageInfo_LanguageKey_Language_ID (length: 10)

        ///<summary>
        /// 詞句Key值
        ///</summary>
        public string MsgKey { get; set; } // MsgKey (length: 500)

        ///<summary>
        /// 內容
        ///</summary>
        public string Msg { get; set; } // Msg (length: 500)
    }

}
// </auto-generated>
