// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ExpressionLab.DB
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class UspGetAnnouncementByIdReturnModel
    {
        public System.Int32 Id { get; set; }
        public System.Int32 CategoryId { get; set; }
        public System.String CategoryName { get; set; }
        public System.String Title { get; set; }
        public System.String ContentSummary { get; set; }
        public System.String ContentDesc { get; set; }
        public System.DateTime EffectiveStartdate { get; set; }
        public System.DateTime EffectiveEnddate { get; set; }
        public System.String BackgroundImagePath { get; set; }
        public System.String CreatorName { get; set; }
        public System.Int32 CreatorDept { get; set; }
        public System.String CreatorDeptName { get; set; }
    }

}
// </auto-generated>
